---
title: "Index_Recruit"
author: "Mauricio Mardones I."
date: "2023-03-20"
output: html_document
---


```{r setup1}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = 'center',
                      dev = 'jpeg',
                      dpi = 300)
#XQuartz is a mess, put this in your onload to default to cairo instead
options(bitmapType = "cairo") 
# (https://github.com/tidyverse/ggplot2/issues/2655)
# Lo mapas se hacen mas rapido
```


```{r warning=F, message=F}
library(tidyverse)
```

Load data

```{r}


names(ohbio6)
dim(ohbio6)
```
## Calculate Index Recruit

```{r}
inderec <- sf4 %>% 
  drop_na(length_total_cm) %>% 
  dplyr::group_by(Year, ID) %>% 
  dplyr::mutate(prolen = length_total_cm - 4.1) %>% 
  dplyr::mutate(prolen2 = prolen*-1 ) %>% 
  dplyr::summarize(prolen3 =mean(prolen2))


limite_superior <- round(mean(inderec$prolen3) + 
  1.96 * sd(inderec$prolen3) / sqrt(inderec$prolen3),3)
limite_inferior <- round(mean(inderec$prolen3) - 
  1.96 * sd(inderec$prolen3) / sqrt(inderec$prolen3),3)
```


```{r}
inderec$colour <- ifelse(inderec$prolen3 < 0, "negative","positive")

indexplot <- ggplot(inderec,
                    aes(rev(Year),prolen3))+
  geom_bar(stat="identity",
           position="identity",
           aes(fill = colour))+
  scale_fill_manual(values=c(positive="firebrick1",
                             negative="black"),
                    name="")+
  facet_wrap(.~ID)+
  theme_few()+
  scale_x_continuous(breaks = seq(from = 2000, 
                                to = 2020, by = 4))+
  theme(axis.text.x = element_text(angle = 90, hjust = 2))+
  labs(y="IRK",
       x="",
       title = "Index Recruit Krill 48.1")
indexplot
```


